"use client";
import { useState, useTransition } from "react";
import type { EventType } from "../types/event";
export function EventTypeAdmin({ initialEventTypes }: { initialEventTypes: EventType[] }) {
  const [eventTypes, setEventTypes] = useState(initialEventTypes); const [name, setName] = useState(""); const [message, setMessage] = useState(""); const [isPending, startTransition] = useTransition();
  async function create() { setMessage(""); const response = await fetch("/api/admin/event-types", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name }) }); const payload = await response.json().catch(() => null) as { data?: EventType; error?: { message?: string } } | null; if (!response.ok || !payload?.data) { setMessage(payload?.error?.message ?? "Impossible d’ajouter ce type."); return; } const created = payload.data; setEventTypes((current) => [...current, created].sort((a, b) => a.name.localeCompare(b.name, "fr"))); setName(""); }
  async function remove(eventType: EventType) { setMessage(""); const response = await fetch(`/api/admin/event-types/${eventType.id}`, { method: "DELETE" }); if (!response.ok) { setMessage("Impossible de supprimer ce type."); return; } setEventTypes((current) => current.filter((item) => item.id !== eventType.id)); }
  return <section className="taxonomy-panel event-type-admin"><div className="taxonomy-panel__heading"><div><h2>Types d’événements</h2><p>Catégories proposées lors de la création et du filtrage des événements.</p></div><span>{eventTypes.length}</span></div><form className="taxonomy-create" onSubmit={(event) => { event.preventDefault(); if (name.trim()) startTransition(create); }}><label className="sr-only" htmlFor="new-event-type">Nouveau type d’événement</label><input disabled={isPending} id="new-event-type" maxLength={80} onChange={(event) => setName(event.target.value)} placeholder="Nouveau type" value={name} /><button className="admin-button admin-button--primary" disabled={isPending || !name.trim()}>Ajouter</button></form>{message ? <p className="form-message" role="alert">{message}</p> : null}{eventTypes.length ? <ul className="taxonomy-list">{eventTypes.map((eventType) => <li key={eventType.id}><span>{eventType.name}</span><div><button className="taxonomy-list__delete" disabled={isPending} onClick={() => { if (window.confirm(`Supprimer « ${eventType.name} » ? Les événements existants ne seront plus typés.`)) startTransition(() => remove(eventType)); }} type="button">Supprimer</button></div></li>)}</ul> : <p className="taxonomy-panel__empty">Aucun type d’événement.</p>}</section>;
}
